# Generated by Django 4.0.5 on 2022-07-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='codigo',
        ),
    ]
