# Generated by Django 4.0.5 on 2022-07-08 06:58

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=sqlalchemy.sql.expression.true, upload_to=''),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
